//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlComplex.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlComplex.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0} is not Found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encoding {0} is invalid: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidEncoding {
            get {
                return ResourceManager.GetString("ErrorInvalidEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line code is invalid: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidLineCode {
            get {
                return ResourceManager.GetString("ErrorInvalidLineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Supported encodings: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpEncoding {
            get {
                return ResourceManager.GetString("HelpEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UTF-8BOM/UTF-16BOM/UTF-16BEBOM/UTF-32BOM/UTF-32BEBOM is supported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpEncodingExt {
            get {
                return ResourceManager.GetString("HelpEncodingExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} -o=exportfile.xml inputfile1.xml inputfile2.xml
        ///Options:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output encoding. default: utf8 (without BOM) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpOptionsEncoding {
            get {
                return ResourceManager.GetString("HelpOptionsEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show supported encodings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpOptionsEncodings {
            get {
                return ResourceManager.GetString("HelpOptionsEncodings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show this message. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpOptionsHelp {
            get {
                return ResourceManager.GetString("HelpOptionsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output with indednt. default:    (double space) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpOptionsIndent {
            get {
                return ResourceManager.GetString("HelpOptionsIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output line break charactor(s). default: CRLF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpOptionsNewLine {
            get {
                return ResourceManager.GetString("HelpOptionsNewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LINECODE: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpOptionsNewLineEx {
            get {
                return ResourceManager.GetString("HelpOptionsNewLineEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output with no indent. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpOptionsNoIndent {
            get {
                return ResourceManager.GetString("HelpOptionsNoIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output file. Specify export file. It is able to set input file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpOptionsOutput {
            get {
                return ResourceManager.GetString("HelpOptionsOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show version. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpOptionsVersion {
            get {
                return ResourceManager.GetString("HelpOptionsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   args: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageArguments {
            get {
                return ResourceManager.GetString("MessageArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Version: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageVersion {
            get {
                return ResourceManager.GetString("MessageVersion", resourceCulture);
            }
        }
    }
}
